In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import datetime
import time
from tqdm import tqdm

In [ ]:
category_tree = pd.read_csv('/content/drive/My Drive/recommender_system/archive/category_tree.csv')
events = pd.read_csv('/content/drive/My Drive/recommender_system/archive/events.csv')

In [3]:
item_properties_part1 = pd.read_csv('/content/drive/My Drive/recommender_system/archive/item_properties_part1.csv')

In [ ]:
item_properties_part2 = pd.read_csv('/content/drive/My Drive/recommender_system/archive/item_properties_part2.csv')

In [ ]:
v_id_824915 = events[events.visitorid == 824915].sort_values('timestamp')

In [ ]:
v_id_824915

           timestamp  visitorid event  itemid  transactionid
15710  1433220801308     824915  view  354365            NaN
473    1433220855897     824915  view  292760            NaN
4454   1433220865962     824915  view  371727            NaN
8      1433220899221     824915  view  428805            NaN
115    1433220908194     824915  view   25427            NaN

In [ ]:
new_df_824915 = pd.DataFrame()

In [ ]:
for j in range(len(v_id_824915)):
  itemid = item_properties_part1[item_properties_part1.itemid == v_id_824915.iloc[j,3]].sort_values('timestamp')
  d1 = v_id_824915.iloc[j,0]
  converted_d1 = datetime.datetime.fromtimestamp(round(d1 / 1000))
  diff = datetime.timedelta(days=1000)
  index = 0
  for i in range(len(itemid)):
    d2 = itemid.iloc[i,0]
    converted_d2 = datetime.datetime.fromtimestamp(round(d2 / 1000))
    if (converted_d1 >= converted_d2) and ((converted_d1 - converted_d2)<=diff):
      diff = converted_d1 - converted_d2
      index = i
  new_df_824915 = new_df_824915.append(itemid[itemid['timestamp'] == itemid.iloc[index,0]])

for j in range(len(v_id_824915)):
  itemid = item_properties_part2[item_properties_part2.itemid == v_id_824915.iloc[j,3]].sort_values('timestamp')
  d1 = v_id_824915.iloc[j,0]
  converted_d1 = datetime.datetime.fromtimestamp(round(d1 / 1000))
  diff = datetime.timedelta(days=1000)
  index = 0
  for i in range(len(itemid)):
    d2 = itemid.iloc[i,0]
    converted_d2 = datetime.datetime.fromtimestamp(round(d2 / 1000))
    if (converted_d1 >= converted_d2) and ((converted_d1 - converted_d2)<=diff):
      diff = converted_d1 - converted_d2
      index = i
  new_df_824915 = new_df_824915.append(itemid[itemid['timestamp'] == itemid.iloc[index,0]])

In [ ]:
new_df_824915 = new_df_824915.drop_duplicates()
new_df_824915

,timestamp,itemid,property,value
6360361,1433041200000,354365,638,n12.000
6759894,1433041200000,354365,790,n128160.000
7463644,1433041200000,354365,636,162622 1033990
10641659,1433041200000,292760,506,961511 1284577 230420
9002262,1433041200000,292760,202,1275486
4241378,1433041200000,292760,955,988697 581051
7982276,1433041200000,292760,1092,291010
8198958,1433041200000,292760,790,n220440.000
2266150,1433041200000,371727,636,162622 1033990
2481012,1433041200000,371727,955,988697 581051
9560802,1433041200000,371727,839,915540
4660890,1433041200000,371727,461,988697 581051
8575961,1433041200000,371727,698,726714
4599016,1433041200000,371727,790,n220440.000
6723015,1433041200000,371727,283,726714 n24.000 1128577 n12.000 915540 1150811 ...
9046176,1433041200000,428805,928,285933
5546689,1433041200000,428805,792,1116693
3152080,1433041200000,428805,698,726714
4593798,1433041200000,428805,888,916731 585138 1284577 110 49574
1181164,1433041200000,428805,790,n237120.000
7207483,1433041200000,25427,495,n180.000
4610165,1433041200000,25427,698,726714
8742881,1433041200000,25427,364,98401
6978119,1433041200000,25427,790,n237120.000
3618276,1433041200000,25427,957,749349
2925426,1433041200000,25427,available,1
406557,1433041200000,25427,678,693826
9003821,1433041200000,25427,955,988697 581051
5886891,1433041200000,25427,776,320446
9154629,1433041200000,354365,775,1116693
7080893,1433041200000,354365,678,4853
1831436,1433041200000,354365,888,58252 961511 1284577 998349
4370154,1433041200000,354365,available,1
7945985,1433041200000,292760,available,1
558519,1433041200000,292760,159,519769
9121267,1433041200000,292760,888,1275486 961511 1284577 230420 868285
421710,1433041200000,371727,888,1150811 1182505 59972 1284577 309080
775023,1433041200000,371727,available,1
2454839,1433041200000,371727,159,519769
4268139,1433041200000,371727,980,1116693
8146404,1433041200000,428805,980,1116693
3132678,1433041200000,428805,955,988697 581051
2299435,1433041200000,428805,638,n12.000
1244028,1433041200000,428805,available,1
5078616,1433041200000,428805,159,519769
448611,1433041200000,428805,506,585138 1284577 110
3208594,1433041200000,428805,678,693826
4766269,1433041200000,25427,112,679677
1380309,1433041200000,25427,928,1133979
8770657,1433041200000,25427,888,97272 916731 726612 648014 1284577 575349

In [4]:
item_prop_1433031200000 = item_properties_part1[item_properties_part1.timestamp == 1433041200000]

In [ ]:
item_prop_1433031200000.shape

(1421070, 4)

In [ ]:
item_prop_1433031200000['property'].unique().shape

(1035,)

In [ ]:
new_df_824915['property'].unique().shape

(24,)

In [ ]:
item_prop_1433031200000['itemid'].unique().shape

(386962,)

In [5]:
one_hot_encode = pd.get_dummies(item_prop_1433031200000,columns=['property'])
one_hot_encode

,timestamp,itemid,value,property_0,property_1,property_10,property_100,property_1000,property_1001,property_1002,...,property_992,property_993,property_994,property_995,property_996,property_997,property_998,property_999,property_available,property_categoryid
76,1433041200000,292458,1141052 n48.000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101,1433041200000,411262,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
102,1433041200000,298275,1322464,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
169,1433041200000,276631,787933 n72492.000 549428,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
176,1433041200000,78556,526492,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10999965,1433041200000,41260,150169 108779,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10999966,1433041200000,15493,1175087 348133,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10999980,1433041200000,251050,n288.000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10999989,1433041200000,56123,452320 853231,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10999990,1433041200000,385426,769062,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
prop_df = pd.DataFrame()

In [14]:
prop_df['itemid'] = one_hot_encode['itemid']

<ipython-input-14-9422654d8ab6>:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  prop_df['itemid'] = one_hot_encode['itemid']

In [15]:
for i in tqdm(range(3,500)):
  mult = one_hot_encode.iloc[:,2]*one_hot_encode.iloc[:,i]
  prop_df[one_hot_encode.columns[i]] = mult

100%|██████████| 497/497 [01:09<00:00,  7.15it/s]

In [ ]:
prop_df.groupby(['itemid']).sum()

In [ ]:
x = item_prop_1433031200000[item_prop_1433031200000.value == '1116693']

In [ ]:
x[x.property == '792']

              timestamp  itemid property    value
10234     1433041200000  271337      792  1116693
40563     1433041200000  461063      792  1116693
44331     1433041200000  218296      792  1116693
56784     1433041200000  316210      792  1116693
63942     1433041200000  165285      792  1116693
...                 ...     ...      ...      ...
10904791  1433041200000  447124      792  1116693
10913843  1433041200000  324794      792  1116693
10939792  1433041200000    6866      792  1116693
10956182  1433041200000  332847      792  1116693
10965635  1433041200000  357326      792  1116693

[721 rows x 4 columns]

In [ ]:
x[x.property == '775']

              timestamp  itemid property    value
30772     1433041200000  100291      775  1116693
34081     1433041200000  283017      775  1116693
40117     1433041200000   34275      775  1116693
50986     1433041200000    9315      775  1116693
71304     1433041200000  334211      775  1116693
...                 ...     ...      ...      ...
10958161  1433041200000  140021      775  1116693
10959552  1433041200000  313274      775  1116693
10965739  1433041200000  348674      775  1116693
10967027  1433041200000  310813      775  1116693
10995165  1433041200000  360802      775  1116693

[652 rows x 4 columns]